# Generated by Django 2.0.4 on 2018-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20180416_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='employee',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда выдан паспорт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='employee',
            name='wing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус'),
        ),
    ]
