# Generated by Django 2.0.4 on 2018-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20180416_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('welcome_text', models.TextField()),
                ('main_text', models.TextField()),
                ('additional_text', models.TextField()),
                ('help_text', models.TextField()),
            ],
        ),
    ]
