# Generated by Django 2.0.4 on 2018-04-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='additional_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='welcome_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
