# Generated by Django 2.0.4 on 2018-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20180524_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, error_messages={'invalid': 'Пожалуйста, введите дату в формате дд.мм.гггг, например: 01.01.1970'}, null=True, verbose_name='Дата рождения'),
        ),
    ]
