# Generated by Django 2.0.4 on 2018-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20180529_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
                ('passport_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер паспорта')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Когда выдан паспорт')),
                ('passport_issued_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан паспорт')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дом')),
                ('wing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус')),
                ('apartment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира')),
                ('date_of_birth', models.DateField(blank=True, error_messages={'invalid': 'this field is invalid'}, null=True, verbose_name='Дата рождения')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер удостоверения')),
                ('license_valid_thru', models.DateField(blank=True, null=True, verbose_name='Удостоверение действительно до')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
    ]
